### ISSUE TITLE
XDG Base Directory Specification　

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [lucasnevespereira/go-gituser#7]
Fixed the directory of the configuration file to `~/.config/gituser/config.json`

ref: https://unix.stackexchange.com/a/313001

**Comment by lucasnevespereira** [comment]
Hello, thanks for checking out the project. This improvement was done by the following commit https://github.com/lucasnevespereira/go-gituser/commit/0b56ea3ec0de6c7faba3dd943ab672440736784f

I'll close this issue 👍🏼
